insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (1, '480', 'Carnitas Burrito Bowl', 'desert', 72.96, 256, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (2, '469', 'Shrimp Scampi', 'predjelo', 69.24, 346, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (3, '96', 'Thai Green Curry', 'predjelo', 89.76, 175, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (4, '313', 'Lemon Pepper Salmon', 'desert', 99.81, 461, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (5, '315', 'Caprese Salad', 'glavno jelo', 20.56, 249, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (6, '281', 'Steak Fajitas', 'predjelo', 69.3, 210, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (7, '8', 'Shrimp Scampi', 'desert', 78.51, 39, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (8, '321', 'Vegetable Stir Fry', 'glavno jelo', 55.08, 230, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (9, '279', 'Lemon Pepper Salmon', 'glavno jelo', 24.18, 358, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (10, '476', 'Chicken and Waffles', 'glavno jelo', 20.24, 324, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (11, '380', 'Crispy Tofu Stir Fry', 'predjelo', 65.0, 168, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (12, '67', 'Teriyaki Salmon', 'glavno jelo', 69.93, 277, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (13, '257', 'Mango Chicken Curry', 'glavno jelo', 42.36, 206, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (14, '367', 'Chicken Alfredo', 'predjelo', 23.07, 264, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (15, '145', 'Lemon Garlic Shrimp Pasta', 'desert', 8.93, 281, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (16, '229', 'Sesame Ginger Noodles', 'desert', 53.22, 474, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (17, '439', 'Butternut Squash Ravioli', 'glavno jelo', 36.12, 347, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (18, '51', 'Lobster Ravioli', 'predjelo', 84.28, 88, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (19, '288', 'Pesto Pasta with Cherry Tomatoes', 'predjelo', 33.28, 118, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (20, '31', 'Sesame Ginger Noodles', 'glavno jelo', 65.73, 148, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (21, '311', 'Lemon Herb Roasted Chicken', 'glavno jelo', 5.24, 246, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (22, '269', 'Thai Green Curry', 'predjelo', 32.89, 267, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (23, '378', 'Vegetable Stir Fry', 'desert', 6.89, 487, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (24, '138', 'Mediterranean Quinoa Salad', 'glavno jelo', 45.98, 331, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (25, '384', 'Mushroom Risotto', 'predjelo', 59.33, 138, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (26, '193', 'Thai Green Curry', 'predjelo', 63.79, 374, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (27, '259', 'Greek Salad', 'glavno jelo', 86.6, 334, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (28, '120', 'BBQ Pulled Pork Sandwich', 'desert', 77.68, 406, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (29, '204', 'Cajun Jambalaya', 'desert', 95.71, 107, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (30, '252', 'Mushroom Risotto', 'glavno jelo', 85.72, 494, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (31, '82', 'BBQ Pulled Pork Sandwich', 'desert', 70.14, 33, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (32, '393', 'Pork Fried Rice', 'desert', 50.65, 424, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (33, '357', 'Mango Chicken Curry', 'glavno jelo', 12.03, 52, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (34, '440', 'Teriyaki Salmon', 'predjelo', 85.8, 448, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (35, '461', 'Thai Green Curry', 'glavno jelo', 49.35, 165, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (36, '495', 'Thai Green Curry', 'glavno jelo', 73.57, 180, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (37, '143', 'Mediterranean Quinoa Salad', 'predjelo', 56.71, 457, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (38, '301', 'Vegetable Stir Fry', 'predjelo', 7.42, 140, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (39, '119', 'Vegetable Curry', 'desert', 72.92, 329, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (40, '265', 'Caprese Salad', 'desert', 7.04, 287, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (41, '417', 'Caprese Salad', 'desert', 34.14, 145, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (42, '238', 'Shrimp Scampi', 'desert', 27.27, 53, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (43, '263', 'Beef Tacos', 'desert', 82.58, 255, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (44, '157', 'Carnitas Burrito Bowl', 'glavno jelo', 30.61, 190, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (45, '180', 'Beef Stroganoff', 'desert', 5.17, 101, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (46, '402', 'Chicken Tikka Masala', 'desert', 8.55, 139, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (47, '415', 'Greek Salad', 'desert', 23.62, 285, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (48, '335', 'Thai Green Curry', 'predjelo', 27.25, 51, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (49, '187', 'Beef Tacos', 'glavno jelo', 95.2, 118, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (50, '349', 'Lemon Herb Roasted Chicken', 'predjelo', 61.12, 342, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (51, '57', 'Vegetable Stir Fry', 'predjelo', 38.02, 210, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (52, '205', 'Spinach and Feta Stuffed Chicken', 'predjelo', 48.08, 194, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (53, '499', 'Hawaiian Pizza', 'desert', 52.5, 349, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (54, '447', 'Mango Chicken Curry', 'predjelo', 33.77, 350, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (55, '225', 'Chicken and Waffles', 'predjelo', 42.04, 357, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (56, '489', 'Pork Carnitas Tacos', 'desert', 68.22, 192, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (57, '332', 'Chicken Tikka Masala', 'predjelo', 21.88, 453, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (58, '94', 'Hawaiian Pizza', 'predjelo', 65.72, 85, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (59, '479', 'Steak Fajitas', 'predjelo', 46.5, 414, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (60, '6', 'Lobster Ravioli', 'glavno jelo', 37.3, 134, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (61, '88', 'Shrimp Tacos', 'predjelo', 50.95, 287, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (62, '71', 'Butternut Squash Ravioli', 'glavno jelo', 47.04, 220, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (63, '109', 'Spinach and Feta Stuffed Chicken', 'glavno jelo', 21.86, 433, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (64, '271', 'Beef Tacos', 'glavno jelo', 65.65, 255, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (65, '98', 'Chicken Alfredo', 'predjelo', 46.0, 170, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (66, '27', 'Crispy Tofu Stir Fry', 'glavno jelo', 79.05, 275, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (67, '164', 'Vegetable Curry', 'desert', 30.34, 390, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (68, '446', 'Crispy Tofu Stir Fry', 'glavno jelo', 14.38, 303, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (69, '498', 'Chicken Parmesan', 'predjelo', 59.62, 172, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (70, '137', 'Cajun Jambalaya', 'desert', 74.53, 50, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (71, '241', 'Lobster Ravioli', 'predjelo', 25.53, 244, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (72, '68', 'Vegetable Curry', 'predjelo', 39.58, 249, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (73, '273', 'Butternut Squash Ravioli', 'predjelo', 5.29, 188, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (74, '210', 'Vegetable Curry', 'desert', 47.02, 46, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (75, '358', 'Pork Fried Rice', 'predjelo', 55.54, 106, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (76, '254', 'Thai Green Curry', 'desert', 26.75, 134, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (77, '142', 'Mushroom Risotto', 'predjelo', 74.69, 220, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (78, '381', 'Spicy Chicken Stir Fry', 'glavno jelo', 63.68, 78, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (79, '309', 'Greek Salad', 'predjelo', 73.3, 200, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (80, '133', 'Teriyaki Salmon', 'glavno jelo', 6.4, 114, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (81, '422', 'Pork Carnitas Tacos', 'glavno jelo', 18.82, 194, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (82, '244', 'Vegetable Curry', 'glavno jelo', 45.59, 287, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (83, '290', 'Eggplant Parmesan', 'glavno jelo', 85.68, 256, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (84, '235', 'Spinach and Feta Stuffed Chicken', 'predjelo', 93.52, 257, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (85, '153', 'Chicken Alfredo', 'glavno jelo', 53.49, 357, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (86, '467', 'Lemon Garlic Shrimp Pasta', 'predjelo', 71.62, 63, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (87, '379', 'Buffalo Chicken Wrap', 'glavno jelo', 38.18, 299, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (88, '318', 'Mango Chicken Curry', 'desert', 11.08, 192, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (89, '43', 'Mushroom Risotto', 'desert', 52.75, 131, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (90, '158', 'Lemon Herb Roasted Chicken', 'glavno jelo', 5.58, 120, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (91, '50', 'Spinach and Feta Stuffed Chicken', 'desert', 79.93, 351, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (92, '220', 'Vegetarian Pad Thai', 'glavno jelo', 85.06, 124, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (93, '155', 'BBQ Pulled Pork Sandwich', 'predjelo', 46.97, 345, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (94, '436', 'Butternut Squash Ravioli', 'desert', 67.0, 487, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (95, '201', 'Mediterranean Quinoa Salad', 'glavno jelo', 62.13, 132, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (96, '175', 'Lemon Herb Roasted Chicken', 'glavno jelo', 56.35, 169, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (97, '84', 'Pesto Pasta with Cherry Tomatoes', 'predjelo', 41.36, 104, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (98, '333', 'Beef and Broccoli Stir Fry', 'desert', 92.65, 245, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (99, '416', 'Lemon Garlic Shrimp Pasta', 'predjelo', 32.41, 102, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (100, '287', 'Chicken Alfredo', 'glavno jelo', 48.22, 200, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (101, '144', 'Hawaiian Pizza', 'desert', 31.59, 288, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (102, '391', 'Mediterranean Quinoa Salad', 'predjelo', 64.8, 448, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (103, '460', 'Chicken and Waffles', 'glavno jelo', 74.21, 36, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (104, '320', 'Chicken Parmesan', 'glavno jelo', 53.48, 234, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (105, '435', 'Crispy Tofu Stir Fry', 'desert', 66.21, 285, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (106, '232', 'Chicken Alfredo', 'predjelo', 29.1, 467, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (107, '473', 'Beef and Broccoli Stir Fry', 'predjelo', 83.57, 315, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (108, '56', 'Pulled Chicken Sandwich', 'glavno jelo', 68.03, 359, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (109, '186', 'Beef and Broccoli Stir Fry', 'predjelo', 77.55, 435, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (110, '108', 'Spicy Chicken Stir Fry', 'glavno jelo', 58.04, 472, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (111, '267', 'Crispy Tofu Stir Fry', 'glavno jelo', 53.2, 255, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (112, '442', 'Eggplant Parmesan', 'glavno jelo', 67.53, 317, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (113, '86', 'Greek Salad', 'desert', 62.05, 39, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (114, '463', 'Mango Chicken Curry', 'predjelo', 11.8, 455, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (115, '198', 'Steak Fajitas', 'glavno jelo', 66.24, 385, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (116, '230', 'Spicy Chicken Stir Fry', 'glavno jelo', 33.45, 304, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (117, '399', 'Mango Chicken Curry', 'glavno jelo', 38.38, 391, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (118, '386', 'Hawaiian Pizza', 'desert', 45.01, 200, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (119, '26', 'Pesto Pasta with Cherry Tomatoes', 'predjelo', 66.12, 58, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (120, '224', 'Pork Fried Rice', 'desert', 15.6, 260, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (121, '293', 'Pesto Pasta with Cherry Tomatoes', 'glavno jelo', 55.96, 495, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (122, '289', 'Vegetarian Pad Thai', 'desert', 62.55, 126, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (123, '58', 'Mediterranean Quinoa Salad', 'predjelo', 47.2, 472, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (124, '424', 'Vegetable Curry', 'desert', 79.81, 92, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (125, '365', 'Shrimp Scampi', 'glavno jelo', 40.69, 354, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (126, '375', 'Steak Fajitas', 'desert', 8.0, 190, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (127, '218', 'Shrimp Scampi', 'desert', 82.57, 173, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (128, '223', 'Crispy Tofu Stir Fry', 'predjelo', 66.28, 98, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (129, '105', 'Mediterranean Quinoa Salad', 'predjelo', 54.56, 312, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (130, '361', 'Thai Green Curry', 'glavno jelo', 40.9, 408, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (131, '101', 'BBQ Pulled Pork Sandwich', 'predjelo', 29.79, 463, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (132, '470', 'Spicy Chicken Stir Fry', 'glavno jelo', 85.16, 260, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (133, '112', 'Lobster Ravioli', 'glavno jelo', 98.82, 117, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (134, '348', 'Chicken Parmesan', 'desert', 87.05, 351, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (135, '377', 'Chicken Alfredo', 'glavno jelo', 22.53, 276, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (136, '390', 'Beef Tacos', 'glavno jelo', 21.25, 90, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (137, '324', 'Pork Fried Rice', 'glavno jelo', 81.01, 53, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (138, '93', 'Thai Green Curry', 'glavno jelo', 19.96, 339, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (139, '162', 'Pork Carnitas Tacos', 'glavno jelo', 76.84, 70, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (140, '222', 'Lemon Herb Roasted Chicken', 'glavno jelo', 87.51, 416, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (141, '305', 'Beef Stroganoff', 'desert', 55.38, 148, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (142, '500', 'Lemon Pepper Salmon', 'glavno jelo', 26.73, 248, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (143, '184', 'Beef and Broccoli Stir Fry', 'desert', 23.95, 73, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (144, '260', 'BBQ Pulled Pork Sandwich', 'predjelo', 50.84, 359, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (145, '383', 'Eggplant Parmesan', 'desert', 47.86, 331, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (146, '317', 'Teriyaki Salmon', 'predjelo', 47.81, 292, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (147, '214', 'Beef Stroganoff', 'desert', 92.05, 489, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (148, '189', 'Mango Chicken Curry', 'desert', 26.2, 384, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (149, '298', 'Teriyaki Salmon', 'predjelo', 91.9, 368, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (150, '195', 'Steak Fajitas', 'glavno jelo', 28.68, 376, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (151, '396', 'Pork Carnitas Tacos', 'predjelo', 54.33, 399, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (152, '420', 'Chicken Tikka Masala', 'desert', 47.17, 260, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (153, '325', 'Shrimp Tacos', 'desert', 35.88, 420, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (154, '334', 'Teriyaki Salmon', 'desert', 70.28, 44, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (155, '44', 'Eggplant Parmesan', 'desert', 8.96, 492, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (156, '340', 'Sesame Ginger Noodles', 'glavno jelo', 10.69, 272, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (157, '307', 'Carnitas Burrito Bowl', 'glavno jelo', 79.65, 436, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (158, '215', 'Mango Chicken Curry', 'glavno jelo', 36.99, 179, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (159, '21', 'Beef Stroganoff', 'predjelo', 38.24, 371, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (160, '132', 'Sesame Ginger Noodles', 'predjelo', 70.96, 168, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (161, '227', 'Crispy Tofu Stir Fry', 'predjelo', 77.84, 139, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (162, '35', 'BBQ Pulled Pork Sandwich', 'predjelo', 73.63, 116, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (163, '296', 'Eggplant Parmesan', 'glavno jelo', 59.85, 304, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (164, '240', 'Thai Green Curry', 'glavno jelo', 58.25, 239, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (165, '278', 'Pork Fried Rice', 'predjelo', 29.14, 148, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (166, '255', 'Lemon Herb Roasted Chicken', 'desert', 19.01, 271, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (167, '219', 'Beef and Broccoli Stir Fry', 'desert', 37.99, 298, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (168, '12', 'Shrimp Tacos', 'predjelo', 78.01, 470, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (169, '458', 'Eggplant Parmesan', 'desert', 65.56, 144, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (170, '285', 'Pesto Pasta with Cherry Tomatoes', 'desert', 9.25, 400, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (171, '306', 'Carnitas Burrito Bowl', 'glavno jelo', 27.83, 417, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (172, '295', 'Lobster Ravioli', 'desert', 71.26, 89, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (173, '221', 'BBQ Pulled Pork Sandwich', 'predjelo', 60.38, 431, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (174, '300', 'Beef Stroganoff', 'desert', 19.52, 481, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (175, '104', 'Shrimp Tacos', 'glavno jelo', 50.04, 30, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (176, '344', 'Mediterranean Quinoa Salad', 'desert', 93.82, 270, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (177, '266', 'Cajun Jambalaya', 'desert', 39.83, 333, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (178, '237', 'Pork Fried Rice', 'desert', 72.95, 430, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (179, '249', 'Shrimp Tacos', 'predjelo', 30.17, 463, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (180, '197', 'Lemon Herb Roasted Chicken', 'desert', 8.89, 232, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (181, '388', 'Cajun Jambalaya', 'glavno jelo', 51.19, 382, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (182, '330', 'Shrimp Scampi', 'predjelo', 7.56, 431, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (183, '110', 'Crispy Tofu Stir Fry', 'glavno jelo', 72.71, 182, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (184, '316', 'Mediterranean Quinoa Salad', 'predjelo', 84.31, 177, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (185, '154', 'Mango Chicken Curry', 'glavno jelo', 55.17, 271, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (186, '466', 'Shrimp Scampi', 'glavno jelo', 48.96, 54, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (187, '283', 'Sesame Ginger Noodles', 'glavno jelo', 66.9, 110, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (188, '468', 'Chicken Parmesan', 'desert', 75.63, 198, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (189, '366', 'Cajun Jambalaya', 'predjelo', 76.14, 238, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (190, '465', 'Vegetable Curry', 'desert', 66.31, 175, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (191, '181', 'Vegetable Stir Fry', 'glavno jelo', 96.22, 89, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (192, '243', 'Buffalo Chicken Wrap', 'predjelo', 52.97, 433, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (193, '141', 'Mediterranean Quinoa Salad', 'predjelo', 50.83, 46, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (194, '228', 'Pesto Pasta with Cherry Tomatoes', 'glavno jelo', 9.59, 40, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (195, '370', 'Mediterranean Quinoa Salad', 'desert', 17.61, 225, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (196, '13', 'Lobster Ravioli', 'desert', 58.42, 93, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (197, '131', 'Pesto Pasta with Cherry Tomatoes', 'desert', 73.28, 37, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (198, '250', 'Pesto Pasta with Cherry Tomatoes', 'desert', 16.66, 110, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (199, '203', 'Mediterranean Quinoa Salad', 'desert', 27.0, 312, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (200, '236', 'Pesto Pasta with Cherry Tomatoes', 'predjelo', 80.07, 294, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (201, '30', 'Butternut Squash Ravioli', 'desert', 89.88, 198, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (202, '304', 'Steak Fajitas', 'desert', 32.96, 42, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (203, '146', 'Eggplant Parmesan', 'predjelo', 78.08, 390, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (204, '115', 'Pulled Chicken Sandwich', 'glavno jelo', 45.73, 85, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (205, '387', 'Pork Carnitas Tacos', 'predjelo', 70.95, 84, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (206, '455', 'Beef and Broccoli Stir Fry', 'desert', 5.26, 136, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (207, '194', 'BBQ Pulled Pork Sandwich', 'desert', 40.05, 73, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (208, '394', 'Sesame Ginger Noodles', 'desert', 10.98, 57, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (209, '207', 'Vegetable Curry', 'predjelo', 13.44, 392, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (210, '485', 'Beef Tacos', 'glavno jelo', 12.07, 139, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (211, '200', 'Eggplant Parmesan', 'glavno jelo', 50.29, 121, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (212, '234', 'Chicken Parmesan', 'glavno jelo', 69.88, 101, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (213, '277', 'Vegetarian Pad Thai', 'predjelo', 7.1, 174, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (214, '75', 'Spinach and Feta Stuffed Chicken', 'glavno jelo', 51.03, 490, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (215, '359', 'Eggplant Parmesan', 'desert', 45.6, 80, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (216, '319', 'Beef and Broccoli Stir Fry', 'desert', 58.76, 199, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (217, '286', 'BBQ Pulled Pork Sandwich', 'glavno jelo', 22.68, 365, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (218, '421', 'Spicy Chicken Stir Fry', 'desert', 55.27, 412, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (219, '453', 'Chicken Parmesan', 'desert', 10.05, 305, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (220, '174', 'Mediterranean Quinoa Salad', 'desert', 8.26, 469, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (221, '308', 'Chicken and Waffles', 'desert', 59.95, 320, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (222, '226', 'Greek Salad', 'predjelo', 12.19, 317, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (223, '355', 'Pork Fried Rice', 'glavno jelo', 24.14, 232, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (224, '312', 'Lemon Herb Roasted Chicken', 'glavno jelo', 96.56, 134, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (225, '274', 'Steak Fajitas', 'predjelo', 93.36, 480, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (226, '426', 'Shrimp Tacos', 'glavno jelo', 63.33, 412, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (227, '258', 'Lemon Garlic Shrimp Pasta', 'glavno jelo', 79.75, 379, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (228, '339', 'Greek Salad', 'predjelo', 57.99, 319, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (229, '448', 'Lobster Ravioli', 'predjelo', 71.48, 147, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (230, '118', 'Shrimp Scampi', 'desert', 91.51, 206, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (231, '291', 'Steak Fajitas', 'desert', 6.69, 134, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (232, '60', 'Chicken Alfredo', 'glavno jelo', 57.32, 398, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (233, '45', 'Sesame Ginger Noodles', 'desert', 63.42, 427, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (234, '408', 'Chicken Alfredo', 'glavno jelo', 13.47, 142, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (235, '76', 'Vegetable Curry', 'desert', 68.41, 139, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (236, '431', 'Beef Stroganoff', 'glavno jelo', 30.46, 391, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (237, '182', 'Spinach and Feta Stuffed Chicken', 'desert', 59.81, 309, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (238, '159', 'Carnitas Burrito Bowl', 'desert', 51.74, 433, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (239, '151', 'Beef and Broccoli Stir Fry', 'glavno jelo', 58.67, 121, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (240, '97', 'Spicy Chicken Stir Fry', 'glavno jelo', 62.15, 44, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (241, '231', 'Chicken Tikka Masala', 'desert', 90.45, 148, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (242, '493', 'Pork Fried Rice', 'glavno jelo', 39.02, 419, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (243, '55', 'Lemon Pepper Salmon', 'predjelo', 24.94, 383, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (244, '438', 'Pork Carnitas Tacos', 'predjelo', 29.62, 145, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (245, '4', 'Pork Fried Rice', 'glavno jelo', 31.47, 175, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (246, '42', 'Thai Green Curry', 'predjelo', 18.78, 134, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (247, '427', 'Spinach and Feta Stuffed Chicken', 'glavno jelo', 54.84, 389, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (248, '364', 'Vegetable Stir Fry', 'glavno jelo', 64.95, 284, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (249, '247', 'Vegetarian Pad Thai', 'glavno jelo', 54.4, 344, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (250, '22', 'Mango Chicken Curry', 'predjelo', 8.19, 251, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (251, '475', 'Chicken Alfredo', 'glavno jelo', 5.9, 459, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (252, '129', 'Thai Green Curry', 'glavno jelo', 28.4, 431, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (253, '49', 'Hawaiian Pizza', 'desert', 15.55, 206, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (254, '156', 'Pulled Chicken Sandwich', 'predjelo', 41.23, 491, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (255, '329', 'Lemon Garlic Shrimp Pasta', 'glavno jelo', 77.9, 265, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (256, '481', 'Caprese Salad', 'predjelo', 64.29, 412, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (257, '178', 'Greek Salad', 'predjelo', 8.12, 484, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (258, '253', 'Lemon Pepper Salmon', 'predjelo', 43.55, 471, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (259, '18', 'Greek Salad', 'glavno jelo', 82.36, 197, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (260, '190', 'BBQ Pulled Pork Sandwich', 'predjelo', 58.81, 329, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (261, '216', 'Sesame Ginger Noodles', 'predjelo', 85.48, 42, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (262, '392', 'Lemon Garlic Shrimp Pasta', 'desert', 28.86, 426, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (263, '484', 'Hawaiian Pizza', 'glavno jelo', 43.85, 63, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (264, '452', 'Lemon Pepper Salmon', 'predjelo', 52.98, 417, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (265, '353', 'Eggplant Parmesan', 'desert', 46.63, 367, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (266, '471', 'Butternut Squash Ravioli', 'glavno jelo', 55.63, 446, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (267, '376', 'Crispy Tofu Stir Fry', 'predjelo', 25.36, 211, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (268, '114', 'Vegetable Stir Fry', 'glavno jelo', 42.25, 356, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (269, '126', 'BBQ Pulled Pork Sandwich', 'desert', 85.91, 38, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (270, '444', 'Spinach and Feta Stuffed Chicken', 'predjelo', 35.64, 367, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (271, '148', 'Steak Fajitas', 'predjelo', 46.21, 52, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (272, '87', 'Lobster Ravioli', 'glavno jelo', 66.26, 491, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (273, '449', 'Vegetable Curry', 'glavno jelo', 82.48, 271, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (274, '347', 'Lobster Ravioli', 'glavno jelo', 99.73, 254, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (275, '38', 'Steak Fajitas', 'predjelo', 32.55, 164, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (276, '40', 'Crispy Tofu Stir Fry', 'predjelo', 63.85, 206, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (277, '217', 'Spicy Chicken Stir Fry', 'glavno jelo', 71.94, 401, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (278, '66', 'Beef Stroganoff', 'predjelo', 28.01, 243, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (279, '432', 'Shrimp Scampi', 'glavno jelo', 81.55, 445, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (280, '443', 'Shrimp Scampi', 'glavno jelo', 96.02, 95, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (281, '430', 'Vegetable Stir Fry', 'glavno jelo', 56.44, 159, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (282, '331', 'Vegetarian Pad Thai', 'glavno jelo', 65.51, 131, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (283, '437', 'Beef and Broccoli Stir Fry', 'glavno jelo', 24.02, 405, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (284, '69', 'Pork Carnitas Tacos', 'desert', 31.56, 84, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (285, '7', 'Chicken Alfredo', 'glavno jelo', 79.86, 377, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (286, '401', 'Hawaiian Pizza', 'predjelo', 89.82, 385, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (287, '63', 'BBQ Pulled Pork Sandwich', 'predjelo', 54.71, 232, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (288, '39', 'Chicken Alfredo', 'desert', 16.74, 404, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (289, '395', 'Mediterranean Quinoa Salad', 'predjelo', 49.64, 286, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (290, '113', 'Teriyaki Salmon', 'desert', 26.23, 328, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (291, '242', 'Caprese Salad', 'glavno jelo', 57.5, 225, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (292, '111', 'Pesto Pasta with Cherry Tomatoes', 'desert', 71.97, 53, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (293, '117', 'Buffalo Chicken Wrap', 'glavno jelo', 41.72, 424, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (294, '428', 'Vegetable Curry', 'desert', 83.74, 500, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (295, '433', 'Mediterranean Quinoa Salad', 'desert', 72.31, 463, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (296, '47', 'Vegetable Curry', 'glavno jelo', 97.84, 403, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (297, '413', 'Steak Fajitas', 'predjelo', 72.04, 437, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (298, '492', 'Hawaiian Pizza', 'predjelo', 60.97, 248, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (299, '354', 'Crispy Tofu Stir Fry', 'glavno jelo', 61.15, 346, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (300, '29', 'Thai Green Curry', 'glavno jelo', 54.21, 334, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (301, '70', 'Vegetable Stir Fry', 'glavno jelo', 92.2, 330, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (302, '343', 'Beef Stroganoff', 'glavno jelo', 47.93, 288, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (303, '268', 'Vegetarian Pad Thai', 'desert', 7.46, 396, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (304, '64', 'Cajun Jambalaya', 'predjelo', 57.89, 387, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (305, '1', 'Crispy Tofu Stir Fry', 'desert', 9.26, 260, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (306, '233', 'Caprese Salad', 'predjelo', 69.47, 488, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (307, '341', 'Spinach and Feta Stuffed Chicken', 'glavno jelo', 26.46, 66, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (308, '170', 'Crispy Tofu Stir Fry', 'desert', 23.13, 453, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (309, '123', 'Chicken and Waffles', 'desert', 96.52, 131, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (310, '441', 'Mediterranean Quinoa Salad', 'glavno jelo', 58.23, 459, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (311, '196', 'Caprese Salad', 'glavno jelo', 21.3, 181, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (312, '337', 'Sesame Ginger Noodles', 'desert', 86.71, 87, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (313, '457', 'Butternut Squash Ravioli', 'glavno jelo', 89.81, 290, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (314, '80', 'Vegetable Curry', 'predjelo', 56.57, 490, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (315, '461', 'Eggplant Parmesan', 'predjelo', 73.84, 487, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (316, '310', 'Lemon Garlic Shrimp Pasta', 'predjelo', 24.06, 121, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (317, '72', 'Pulled Chicken Sandwich', 'predjelo', 46.17, 188, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (318, '223', 'Hawaiian Pizza', 'desert', 58.99, 420, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (319, '273', 'Chicken Alfredo', 'desert', 66.32, 58, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (320, '26', 'Thai Green Curry', 'predjelo', 72.01, 141, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (321, '406', 'Eggplant Parmesan', 'predjelo', 6.21, 76, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (322, '410', 'Chicken Parmesan', 'predjelo', 16.23, 318, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (323, '354', 'Eggplant Parmesan', 'desert', 82.8, 46, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (324, '190', 'Buffalo Chicken Wrap', 'predjelo', 61.71, 138, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (325, '71', 'Steak Fajitas', 'desert', 47.3, 488, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (326, '350', 'Chicken Parmesan', 'glavno jelo', 38.02, 134, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (327, '217', 'Beef Stroganoff', 'glavno jelo', 60.71, 37, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (328, '144', 'Shrimp Tacos', 'predjelo', 88.71, 273, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (329, '455', 'Cajun Jambalaya', 'predjelo', 47.61, 306, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (330, '169', 'Beef Stroganoff', 'desert', 14.0, 457, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (331, '399', 'Beef Stroganoff', 'predjelo', 7.21, 461, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (332, '25', 'Caprese Salad', 'predjelo', 91.49, 81, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (333, '438', 'Teriyaki Salmon', 'desert', 79.19, 431, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (334, '47', 'Carnitas Burrito Bowl', 'desert', 6.91, 133, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (335, '74', 'Eggplant Parmesan', 'desert', 45.17, 154, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (336, '358', 'Shrimp Tacos', 'desert', 12.68, 303, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (337, '88', 'Butternut Squash Ravioli', 'desert', 40.11, 194, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (338, '499', 'Chicken Tikka Masala', 'predjelo', 51.56, 189, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (339, '142', 'Chicken Tikka Masala', 'desert', 92.45, 149, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (340, '208', 'Mango Chicken Curry', 'glavno jelo', 94.15, 129, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (341, '183', 'Chicken Parmesan', 'predjelo', 89.64, 221, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (342, '309', 'Caprese Salad', 'glavno jelo', 47.57, 164, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (343, '81', 'Spicy Chicken Stir Fry', 'predjelo', 16.05, 33, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (344, '48', 'Vegetable Stir Fry', 'predjelo', 82.58, 89, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (345, '67', 'Vegetarian Pad Thai', 'glavno jelo', 85.41, 151, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (346, '187', 'Crispy Tofu Stir Fry', 'desert', 35.71, 155, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (347, '401', 'Steak Fajitas', 'desert', 15.93, 458, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (348, '289', 'Mediterranean Quinoa Salad', 'desert', 43.96, 263, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (349, '258', 'Chicken Parmesan', 'glavno jelo', 88.84, 419, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (350, '495', 'Thai Green Curry', 'glavno jelo', 14.22, 465, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (351, '452', 'Butternut Squash Ravioli', 'predjelo', 54.27, 377, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (352, '480', 'Spicy Chicken Stir Fry', 'glavno jelo', 53.97, 331, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (353, '330', 'Caprese Salad', 'desert', 5.46, 252, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (354, '61', 'Beef Tacos', 'glavno jelo', 20.13, 227, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (355, '426', 'Buffalo Chicken Wrap', 'glavno jelo', 99.94, 273, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (356, '52', 'Shrimp Scampi', 'glavno jelo', 21.41, 38, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (357, '216', 'Carnitas Burrito Bowl', 'desert', 64.24, 268, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (358, '283', 'Shrimp Tacos', 'desert', 94.82, 257, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (359, '487', 'Steak Fajitas', 'desert', 19.92, 336, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (360, '118', 'Pesto Pasta with Cherry Tomatoes', 'predjelo', 33.34, 371, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (361, '10', 'Carnitas Burrito Bowl', 'glavno jelo', 25.71, 285, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (362, '133', 'Beef Stroganoff', 'glavno jelo', 39.59, 377, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (363, '478', 'Steak Fajitas', 'desert', 96.36, 37, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (364, '17', 'Chicken Parmesan', 'predjelo', 75.81, 367, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (365, '69', 'Buffalo Chicken Wrap', 'desert', 84.52, 195, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (366, '119', 'Spinach and Feta Stuffed Chicken', 'glavno jelo', 66.43, 338, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (367, '3', 'Hawaiian Pizza', 'glavno jelo', 71.33, 192, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (368, '70', 'Pulled Chicken Sandwich', 'glavno jelo', 64.69, 296, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (369, '417', 'Sesame Ginger Noodles', 'predjelo', 97.98, 50, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (370, '193', 'Mediterranean Quinoa Salad', 'desert', 65.55, 393, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (371, '229', 'Chicken Tikka Masala', 'desert', 69.68, 237, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (372, '473', 'Beef Tacos', 'glavno jelo', 40.39, 493, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (373, '40', 'Hawaiian Pizza', 'desert', 76.86, 263, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (374, '100', 'Spinach and Feta Stuffed Chicken', 'desert', 60.79, 206, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (375, '341', 'Mediterranean Quinoa Salad', 'predjelo', 43.51, 481, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (376, '164', 'Beef Tacos', 'desert', 75.18, 488, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (377, '462', 'Teriyaki Salmon', 'glavno jelo', 5.4, 410, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (378, '170', 'Lemon Herb Roasted Chicken', 'desert', 20.84, 352, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (379, '494', 'Spicy Chicken Stir Fry', 'predjelo', 49.07, 59, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (380, '300', 'Lemon Garlic Shrimp Pasta', 'predjelo', 20.52, 83, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (381, '5', 'Greek Salad', 'desert', 50.5, 434, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (382, '319', 'Pulled Chicken Sandwich', 'predjelo', 37.68, 419, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (383, '404', 'Mushroom Risotto', 'glavno jelo', 59.51, 221, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (384, '428', 'Lobster Ravioli', 'desert', 80.09, 243, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (385, '114', 'Vegetarian Pad Thai', 'desert', 25.23, 447, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (386, '214', 'Spinach and Feta Stuffed Chicken', 'glavno jelo', 60.75, 54, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (387, '376', 'Beef Tacos', 'desert', 95.74, 309, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (388, '498', 'Vegetarian Pad Thai', 'predjelo', 83.23, 386, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (389, '394', 'Vegetable Curry', 'glavno jelo', 22.97, 458, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (390, '356', 'Pork Fried Rice', 'glavno jelo', 44.94, 41, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (391, '87', 'Chicken Parmesan', 'predjelo', 55.26, 412, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (392, '409', 'Beef Tacos', 'desert', 48.4, 453, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (393, '360', 'Buffalo Chicken Wrap', 'desert', 75.11, 261, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (394, '101', 'Chicken and Waffles', 'glavno jelo', 20.24, 173, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (395, '194', 'Lemon Pepper Salmon', 'predjelo', 28.99, 42, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (396, '306', 'Beef and Broccoli Stir Fry', 'glavno jelo', 88.53, 194, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (397, '408', 'Vegetable Stir Fry', 'desert', 38.44, 225, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (398, '64', 'Mango Chicken Curry', 'glavno jelo', 57.88, 341, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (399, '30', 'Pork Carnitas Tacos', 'glavno jelo', 58.74, 32, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (400, '357', 'Hawaiian Pizza', 'glavno jelo', 43.18, 61, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (401, '99', 'Cajun Jambalaya', 'glavno jelo', 70.92, 336, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (402, '333', 'Thai Green Curry', 'desert', 66.79, 288, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (403, '246', 'Crispy Tofu Stir Fry', 'predjelo', 44.4, 163, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (404, '488', 'Shrimp Scampi', 'glavno jelo', 18.43, 242, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (405, '254', 'Spicy Chicken Stir Fry', 'desert', 98.63, 143, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (406, '117', 'Lemon Pepper Salmon', 'predjelo', 97.61, 241, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (407, '107', 'Greek Salad', 'desert', 97.59, 194, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (408, '365', 'Greek Salad', 'predjelo', 33.81, 480, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (409, '127', 'Cajun Jambalaya', 'desert', 6.21, 46, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (410, '230', 'Pulled Chicken Sandwich', 'desert', 17.75, 496, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (411, '474', 'Cajun Jambalaya', 'glavno jelo', 24.43, 496, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (412, '123', 'Beef and Broccoli Stir Fry', 'predjelo', 73.81, 298, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (413, '82', 'Butternut Squash Ravioli', 'desert', 73.29, 460, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (414, '381', 'Greek Salad', 'desert', 16.07, 112, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (415, '149', 'Eggplant Parmesan', 'predjelo', 79.96, 57, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (416, '85', 'Lemon Pepper Salmon', 'predjelo', 83.74, 327, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (417, '63', 'Buffalo Chicken Wrap', 'predjelo', 7.15, 200, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (418, '173', 'Pulled Chicken Sandwich', 'desert', 67.32, 405, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (419, '490', 'Buffalo Chicken Wrap', 'desert', 66.81, 284, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (420, '345', 'Vegetable Curry', 'predjelo', 68.8, 371, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (421, '374', 'Greek Salad', 'predjelo', 89.5, 151, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (422, '325', 'Butternut Squash Ravioli', 'predjelo', 94.0, 322, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (423, '210', 'Carnitas Burrito Bowl', 'glavno jelo', 17.8, 159, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (424, '368', 'Buffalo Chicken Wrap', 'predjelo', 9.65, 433, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (425, '311', 'Crispy Tofu Stir Fry', 'glavno jelo', 9.59, 342, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (426, '326', 'Crispy Tofu Stir Fry', 'desert', 6.97, 495, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (427, '244', 'Pork Carnitas Tacos', 'predjelo', 82.98, 103, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (428, '290', 'Butternut Squash Ravioli', 'predjelo', 32.44, 400, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (429, '457', 'Pork Carnitas Tacos', 'predjelo', 33.52, 223, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (430, '59', 'Mango Chicken Curry', 'predjelo', 90.72, 262, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (431, '355', 'Chicken Tikka Masala', 'desert', 38.62, 477, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (432, '277', 'Lemon Garlic Shrimp Pasta', 'predjelo', 89.79, 299, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (433, '307', 'Mushroom Risotto', 'desert', 58.47, 354, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (434, '156', 'Mango Chicken Curry', 'predjelo', 18.08, 284, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (435, '429', 'Vegetarian Pad Thai', 'predjelo', 30.98, 90, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (436, '141', 'Pork Fried Rice', 'predjelo', 16.81, 228, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (437, '337', 'Sesame Ginger Noodles', 'predjelo', 9.26, 415, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (438, '105', 'Beef Tacos', 'predjelo', 20.37, 204, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (439, '386', 'Pesto Pasta with Cherry Tomatoes', 'desert', 30.49, 127, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (440, '295', 'Hawaiian Pizza', 'glavno jelo', 49.34, 341, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (441, '382', 'Mango Chicken Curry', 'predjelo', 87.96, 218, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (442, '97', 'Pulled Chicken Sandwich', 'desert', 67.65, 256, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (443, '189', 'Lobster Ravioli', 'glavno jelo', 98.57, 465, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (444, '375', 'Lemon Garlic Shrimp Pasta', 'glavno jelo', 5.78, 107, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (445, '135', 'Lemon Herb Roasted Chicken', 'glavno jelo', 36.62, 294, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (446, '182', 'Shrimp Tacos', 'glavno jelo', 92.13, 132, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (447, '148', 'Chicken Alfredo', 'desert', 87.08, 443, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (448, '385', 'Beef Tacos', 'glavno jelo', 82.55, 214, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (449, '259', 'Mango Chicken Curry', 'desert', 32.34, 255, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (450, '37', 'Hawaiian Pizza', 'desert', 79.08, 38, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (451, '492', 'BBQ Pulled Pork Sandwich', 'desert', 32.99, 200, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (452, '225', 'Hawaiian Pizza', 'predjelo', 76.72, 161, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (453, '153', 'Cajun Jambalaya', 'desert', 10.74, 300, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (454, '50', 'Greek Salad', 'predjelo', 73.8, 91, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (455, '111', 'Teriyaki Salmon', 'desert', 9.72, 495, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (456, '321', 'Eggplant Parmesan', 'predjelo', 59.75, 120, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (457, '181', 'Shrimp Tacos', 'desert', 33.63, 181, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (458, '416', 'Mushroom Risotto', 'glavno jelo', 59.08, 358, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (459, '227', 'Lemon Herb Roasted Chicken', 'glavno jelo', 70.42, 445, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (460, '255', 'Chicken Alfredo', 'predjelo', 83.58, 416, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (461, '110', 'Chicken and Waffles', 'predjelo', 94.33, 34, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (462, '58', 'Shrimp Scampi', 'desert', 88.69, 185, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (463, '235', 'Pesto Pasta with Cherry Tomatoes', 'desert', 12.72, 414, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (464, '145', 'Beef Stroganoff', 'predjelo', 91.85, 432, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (465, '459', 'Beef and Broccoli Stir Fry', 'predjelo', 20.82, 468, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (466, '236', 'Carnitas Burrito Bowl', 'glavno jelo', 51.37, 168, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (467, '471', 'Chicken and Waffles', 'desert', 94.63, 152, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (468, '128', 'Beef Stroganoff', 'predjelo', 87.61, 373, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (469, '7', 'Pesto Pasta with Cherry Tomatoes', 'predjelo', 92.03, 438, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (470, '436', 'Cajun Jambalaya', 'predjelo', 33.06, 310, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (471, '407', 'Carnitas Burrito Bowl', 'glavno jelo', 76.22, 101, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (472, '393', 'Chicken Tikka Masala', 'predjelo', 74.28, 197, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (473, '219', 'Pesto Pasta with Cherry Tomatoes', 'desert', 71.57, 182, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (474, '161', 'Mediterranean Quinoa Salad', 'glavno jelo', 88.27, 384, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (475, '15', 'Chicken Tikka Masala', 'predjelo', 75.34, 136, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (476, '297', 'Pork Carnitas Tacos', 'desert', 62.01, 309, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (477, '413', 'Lemon Herb Roasted Chicken', 'predjelo', 48.37, 212, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (478, '65', 'Vegetable Stir Fry', 'glavno jelo', 37.13, 306, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (479, '304', 'Beef Stroganoff', 'desert', 66.2, 119, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (480, '484', 'Greek Salad', 'predjelo', 75.49, 232, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (481, '279', 'Chicken Tikka Masala', 'desert', 76.11, 391, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (482, '282', 'Pork Fried Rice', 'desert', 86.39, 178, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (483, '335', 'Cajun Jambalaya', 'glavno jelo', 76.31, 200, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (484, '36', 'Shrimp Tacos', 'glavno jelo', 56.23, 497, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (485, '331', 'Pulled Chicken Sandwich', 'predjelo', 26.92, 156, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (486, '411', 'Lemon Pepper Salmon', 'glavno jelo', 22.35, 487, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (487, '9', 'Lemon Garlic Shrimp Pasta', 'glavno jelo', 70.63, 256, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (488, '362', 'Buffalo Chicken Wrap', 'glavno jelo', 35.57, 135, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (489, '209', 'Vegetable Stir Fry', 'predjelo', 77.87, 346, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (490, '184', 'Lemon Pepper Salmon', 'desert', 7.78, 389, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (491, '431', 'Chicken Alfredo', 'desert', 84.7, 365, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (492, '456', 'Cajun Jambalaya', 'desert', 39.95, 30, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (493, '197', 'Spinach and Feta Stuffed Chicken', 'predjelo', 48.81, 270, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (494, '372', 'Shrimp Tacos', 'glavno jelo', 73.82, 159, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (495, '224', 'Lemon Garlic Shrimp Pasta', 'desert', 87.37, 352, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (496, '228', 'Beef Tacos', 'glavno jelo', 81.26, 479, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (497, '249', 'Shrimp Tacos', 'predjelo', 85.11, 262, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (498, '445', 'Pork Carnitas Tacos', 'predjelo', 52.42, 69, false);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (499, '418', 'Sesame Ginger Noodles', 'predjelo', 97.27, 274, true);
insert into Dish (DishId, RestaurantId, DishName, DishCategory, Price, CalorieValue, Available) values (500, '352', 'Butternut Squash Ravioli', 'desert', 34.83, 163, true);
