insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (1, 'Rayner', 'Hannon', 'Istarska ulica 3', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (2, 'Eldredge', 'Wakeford', 'Istarska ulica 3', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (3, 'Paddy', 'McTeggart', 'Dalmatinska ulica 7', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (4, 'Chrystel', 'Haliburton', 'Osijek', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (5, 'Milty', 'Grote', 'Pula', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (6, 'Jackie', 'Tomkies', 'Istarska ulica 3', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (7, 'Charlton', 'Cleveley', 'Istarska ulica 3', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (8, 'Keen', 'Crab', 'Slavonska ulica 10', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (9, 'Sheila', 'Glass', 'Pula', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (10, 'Hewe', 'Elgie', 'Jadranska ulica 5', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (11, 'Harriott', 'Bonnefin', 'Zadar', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (12, 'Hesther', 'Worssam', 'Dalmatinska ulica 7', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (13, 'Kissee', 'Morando', 'Split', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (14, 'Lynette', 'Kimbley', 'Split', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (15, 'Jack', 'Habeshaw', 'Dalmatinska ulica 7', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (16, 'Farr', 'Adhams', 'Dalmatinska ulica 7', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (17, 'Harrietta', 'MacVagh', 'Zadar', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (18, 'Ronalda', 'McIver', 'Zadar', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (19, 'Valentina', 'Shafe', 'Zagrebačka ulica 1', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (20, 'Verene', 'Spriddle', 'Istarska ulica 3', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (21, 'Patsy', 'Tremblot', 'Zagrebačka ulica 1', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (22, 'Jody', 'Forkan', 'Split', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (23, 'Tanhya', 'Kupec', 'Split', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (24, 'Tiebout', 'Bebis', 'Zagreb', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (25, 'Lanita', 'Peto', 'Jadranska ulica 5', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (26, 'Berni', 'Ottee', 'Jadranska ulica 5', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (27, 'Mar', 'Hackforth', 'Osijek', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (28, 'Kiersten', 'Swainson', 'Istarska ulica 3', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (29, 'Marla', 'Caulder', 'Split', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (30, 'Noll', 'Pittman', 'Slavonska ulica 10', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (31, 'Franchot', 'Pryn', 'Osijek', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (32, 'Drud', 'Ovitz', 'Split', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (33, 'Cyril', 'Llewhellin', 'Split', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (34, 'Thekla', 'Golland', 'Pula', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (35, 'Romeo', 'Hiland', 'Zagrebačka ulica 1', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (36, 'Esdras', 'Isakowicz', 'Pula', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (37, 'Merci', 'Reitenbach', 'Slavonska ulica 10', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (38, 'Tommie', 'Keywood', 'Zadar', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (39, 'Bernarr', 'Leiden', 'Jadranska ulica 5', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (40, 'Montague', 'Gussie', 'Zagrebačka ulica 1', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (41, 'Elly', 'Fontel', 'Zagrebačka ulica 1', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (42, 'Doloritas', 'Bilofsky', 'Osijek', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (43, 'Justine', 'Dinkin', 'Istarska ulica 3', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (44, 'Friedrich', 'Swinbourne', 'Jadranska ulica 5', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (45, 'Lemmy', 'Beddo', 'Zadar', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (46, 'Davon', 'Dami', 'Jadranska ulica 5', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (47, 'Pieter', 'Measor', 'Zagrebačka ulica 1', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (48, 'Willi', 'Lauridsen', 'Osijek', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (49, 'Dukie', 'Zebedee', 'Istarska ulica 3', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (50, 'Tyler', 'Finby', 'Zagreb', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (51, 'Malvin', 'Lovatt', 'Zagrebačka ulica 1', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (52, 'Richy', 'Grunbaum', 'Zagreb', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (53, 'Innis', 'Bearman', 'Zagrebačka ulica 1', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (54, 'Taite', 'Mazella', 'Zadar', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (55, 'Thurstan', 'Sills', 'Split', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (56, 'Wald', 'Tresvina', 'Osijek', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (57, 'Christabel', 'Ramsey', 'Istarska ulica 3', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (58, 'Ashien', 'Gladwell', 'Pula', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (59, 'Wenonah', 'Tureville', 'Pula', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (60, 'Karalee', 'Sidnell', 'Pula', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (61, 'Brittany', 'Krier', 'Osijek', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (62, 'Cristal', 'Vaszoly', 'Split', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (63, 'Hermy', 'Hammerton', 'Jadranska ulica 5', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (64, 'Alistair', 'Fass', 'Zagrebačka ulica 1', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (65, 'Arleta', 'McIlwaine', 'Zagreb', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (66, 'Olivero', 'Grellier', 'Pula', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (67, 'Dusty', 'Keysel', 'Dalmatinska ulica 7', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (68, 'Ileane', 'Nail', 'Dalmatinska ulica 7', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (69, 'Alleen', 'Clewley', 'Osijek', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (70, 'Eachelle', 'Fitzsimons', 'Jadranska ulica 5', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (71, 'Malinda', 'Barnett', 'Osijek', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (72, 'Lorry', 'Bartalin', 'Split', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (73, 'Carlotta', 'Heartfield', 'Slavonska ulica 10', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (74, 'Patty', 'Norton', 'Zagreb', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (75, 'Thea', 'Spellesy', 'Pula', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (76, 'Lalo', 'Devoy', 'Zagreb', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (77, 'Darsey', 'Alsford', 'Osijek', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (78, 'Trumann', 'Kock', 'Jadranska ulica 5', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (79, 'Archibald', 'Velti', 'Zadar', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (80, 'Nicolis', 'Waddicor', 'Dalmatinska ulica 7', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (81, 'Rodolphe', 'Semkins', 'Osijek', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (82, 'Arleta', 'Jeffrey', 'Osijek', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (83, 'Shana', 'Denisyuk', 'Split', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (84, 'Selma', 'Philipeaux', 'Dalmatinska ulica 7', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (85, 'Indira', 'Real', 'Dalmatinska ulica 7', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (86, 'Karmen', 'Craze', 'Dalmatinska ulica 7', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (87, 'Justino', 'Coopey', 'Zadar', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (88, 'Estelle', 'Yakov', 'Split', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (89, 'Farris', 'Marxsen', 'Zadar', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (90, 'Gisella', 'Tosspell', 'Jadranska ulica 5', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (91, 'Norene', 'Buckle', 'Zadar', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (92, 'Kim', 'Noirel', 'Osijek', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (93, 'Alard', 'Mosdell', 'Pula', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (94, 'Natalee', 'Blaycock', 'Dalmatinska ulica 7', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (95, 'Boniface', 'Duckett', 'Split', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (96, 'Karna', 'Dowthwaite', 'Dalmatinska ulica 7', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (97, 'Gardner', 'McIlwreath', 'Osijek', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (98, 'Ardene', 'Malham', 'Jadranska ulica 5', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (99, 'Jordon', 'McAvinchey', 'Slavonska ulica 10', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (100, 'Ario', 'Whitehair', 'Pula', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (101, 'Kimberli', 'Conti', 'Zagrebačka ulica 1', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (102, 'Margaret', 'Wallbridge', 'Dalmatinska ulica 7', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (103, 'Maddalena', 'Mander', 'Zagrebačka ulica 1', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (104, 'Merci', 'Cancellor', 'Osijek', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (105, 'Erastus', 'Wadham', 'Split', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (106, 'Lavinie', 'Gwynne', 'Slavonska ulica 10', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (107, 'Lamont', 'Kimbrey', 'Slavonska ulica 10', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (108, 'Milena', 'Plumm', 'Pula', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (109, 'Tonie', 'Broadhurst', 'Split', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (110, 'Gian', 'Coolahan', 'Jadranska ulica 5', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (111, 'Callean', 'Gravener', 'Split', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (112, 'Arlyne', 'Killigrew', 'Zagrebačka ulica 1', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (113, 'Ciro', 'Wylie', 'Dalmatinska ulica 7', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (114, 'Althea', 'Roddy', 'Dalmatinska ulica 7', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (115, 'Phineas', 'Scoines', 'Istarska ulica 3', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (116, 'Ginger', 'O''Sherin', 'Zadar', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (117, 'Richard', 'Haswall', 'Slavonska ulica 10', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (118, 'Norrie', 'Gentsch', 'Dalmatinska ulica 7', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (119, 'Theadora', 'Murrhardt', 'Split', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (120, 'Marsh', 'Follows', 'Dalmatinska ulica 7', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (121, 'Yance', 'Boddymead', 'Split', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (122, 'Sherry', 'Collister', 'Split', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (123, 'Denyse', 'Rosevear', 'Zagreb', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (124, 'Hans', 'Greatorex', 'Pula', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (125, 'Stephine', 'Wile', 'Pula', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (126, 'Gwyn', 'McChruiter', 'Split', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (127, 'Monique', 'Swanne', 'Split', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (128, 'Desdemona', 'Joutapaitis', 'Dalmatinska ulica 7', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (129, 'Marin', 'Lintott', 'Split', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (130, 'Amelina', 'Cuerdale', 'Zagrebačka ulica 1', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (131, 'Regan', 'Jillitt', 'Dalmatinska ulica 7', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (132, 'Drusilla', 'Sarfat', 'Pula', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (133, 'Binni', 'Kingerby', 'Split', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (134, 'Vladamir', 'Adenot', 'Pula', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (135, 'Susette', 'Gutierrez', 'Zagrebačka ulica 1', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (136, 'Mirabelle', 'Harroll', 'Istarska ulica 3', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (137, 'Cari', 'Bispham', 'Osijek', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (138, 'Frederik', 'Rawcliffe', 'Osijek', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (139, 'Miner', 'Halkyard', 'Zagreb', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (140, 'Janela', 'Minger', 'Jadranska ulica 5', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (141, 'Siegfried', 'Thornbarrow', 'Osijek', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (142, 'Abeu', 'Wychard', 'Dalmatinska ulica 7', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (143, 'Issie', 'Babinski', 'Zagrebačka ulica 1', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (144, 'Gibby', 'Heberden', 'Slavonska ulica 10', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (145, 'Shannan', 'Khilkov', 'Istarska ulica 3', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (146, 'Karita', 'Pettican', 'Osijek', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (147, 'Findley', 'Gossage', 'Slavonska ulica 10', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (148, 'Thorsten', 'Divell', 'Zagrebačka ulica 1', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (149, 'Bree', 'Cominotti', 'Zagreb', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (150, 'Hayley', 'Neal', 'Zagrebačka ulica 1', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (151, 'Tani', 'Ronaldson', 'Pula', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (152, 'Prince', 'Morit', 'Zagrebačka ulica 1', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (153, 'Gerri', 'Dorie', 'Jadranska ulica 5', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (154, 'Rickie', 'Hovell', 'Osijek', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (155, 'Juli', 'Blaise', 'Istarska ulica 3', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (156, 'Laney', 'Gounot', 'Jadranska ulica 5', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (157, 'Lexy', 'Rockhill', 'Jadranska ulica 5', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (158, 'Abdul', 'Thickett', 'Zagreb', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (159, 'Shelli', 'Keitley', 'Zagreb', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (160, 'Peter', 'Duesberry', 'Zagreb', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (161, 'Tristam', 'Olesen', 'Jadranska ulica 5', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (162, 'Lowrance', 'Merredy', 'Zadar', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (163, 'Cooper', 'Campsall', 'Osijek', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (164, 'Sabine', 'Bosward', 'Zagrebačka ulica 1', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (165, 'Randolph', 'Amori', 'Pula', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (166, 'Thomasa', 'Halgarth', 'Pula', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (167, 'Adrianna', 'Bauman', 'Pula', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (168, 'Arte', 'Woodeson', 'Zadar', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (169, 'Eugen', 'Basnett', 'Zagreb', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (170, 'Roscoe', 'Medina', 'Split', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (171, 'Riane', 'Gwilliams', 'Jadranska ulica 5', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (172, 'Sampson', 'Blagbrough', 'Jadranska ulica 5', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (173, 'Karna', 'Dowty', 'Zagrebačka ulica 1', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (174, 'Derek', 'Glassford', 'Jadranska ulica 5', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (175, 'Yank', 'Fosdyke', 'Zagreb', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (176, 'Gabey', 'Crackel', 'Zadar', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (177, 'Berkly', 'Pegrum', 'Istarska ulica 3', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (178, 'Ginnie', 'Siney', 'Istarska ulica 3', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (179, 'Leslie', 'Reddish', 'Zagrebačka ulica 1', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (180, 'Danila', 'Klaggeman', 'Pula', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (181, 'Randolph', 'Admans', 'Split', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (182, 'Nettle', 'Francom', 'Slavonska ulica 10', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (183, 'Rouvin', 'Gisburn', 'Jadranska ulica 5', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (184, 'Kiah', 'Daber', 'Jadranska ulica 5', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (185, 'Sonny', 'Baythorp', 'Jadranska ulica 5', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (186, 'Jarred', 'Sedgebeer', 'Pula', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (187, 'Fidelity', 'Medler', 'Slavonska ulica 10', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (188, 'Weylin', 'Cecchi', 'Slavonska ulica 10', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (189, 'Anastasia', 'Ladyman', 'Split', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (190, 'Alla', 'McPhelim', 'Istarska ulica 3', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (191, 'Jason', 'McAnalley', 'Zagrebačka ulica 1', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (192, 'Mateo', 'Petyankin', 'Split', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (193, 'Frederique', 'Pembridge', 'Dalmatinska ulica 7', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (194, 'Charlotta', 'Rawne', 'Jadranska ulica 5', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (195, 'Zola', 'Semonin', 'Dalmatinska ulica 7', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (196, 'Killy', 'Myall', 'Pula', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (197, 'Haslett', 'Lude', 'Zadar', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (198, 'Langston', 'Fiddeman', 'Split', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (199, 'Gael', 'O''Cosgra', 'Zagrebačka ulica 1', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (200, 'Currie', 'Horsefield', 'Osijek', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (201, 'Solly', 'Keets', 'Osijek', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (202, 'Miguel', 'Anfusso', 'Dalmatinska ulica 7', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (203, 'Kimberly', 'Dobbing', 'Zagreb', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (204, 'Selby', 'Lytell', 'Jadranska ulica 5', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (205, 'Jocelyn', 'Boles', 'Slavonska ulica 10', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (206, 'Peggy', 'Genike', 'Split', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (207, 'Desmond', 'Sondon', 'Zagrebačka ulica 1', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (208, 'Shelia', 'Persicke', 'Zagreb', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (209, 'Davis', 'Tregona', 'Istarska ulica 3', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (210, 'Tabbie', 'Gounel', 'Zadar', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (211, 'Poul', 'Arnefield', 'Zagrebačka ulica 1', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (212, 'Liv', 'Honack', 'Osijek', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (213, 'Loren', 'Beane', 'Slavonska ulica 10', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (214, 'Rube', 'Mosby', 'Zadar', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (215, 'Thaddeus', 'Tidswell', 'Dalmatinska ulica 7', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (216, 'Ilyse', 'Scoggin', 'Zadar', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (217, 'Charlton', 'Sute', 'Split', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (218, 'Essie', 'Horbart', 'Zadar', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (219, 'Ezechiel', 'Ingles', 'Jadranska ulica 5', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (220, 'Clarke', 'Lambkin', 'Istarska ulica 3', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (221, 'Fee', 'Duny', 'Zagrebačka ulica 1', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (222, 'Magdalen', 'Orae', 'Pula', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (223, 'Obie', 'Sailor', 'Slavonska ulica 10', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (224, 'Geoffry', 'Linch', 'Istarska ulica 3', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (225, 'Aldon', 'Mordecai', 'Istarska ulica 3', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (226, 'Davin', 'Hindenberger', 'Split', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (227, 'Phaedra', 'Kunkel', 'Osijek', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (228, 'Alden', 'Synke', 'Istarska ulica 3', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (229, 'Yvor', 'Ludford', 'Pula', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (230, 'Domenic', 'Tanner', 'Zagreb', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (231, 'Connor', 'Tweddle', 'Zagreb', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (232, 'Boot', 'Kochel', 'Split', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (233, 'Peria', 'Reichartz', 'Dalmatinska ulica 7', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (234, 'Marty', 'MacLucais', 'Dalmatinska ulica 7', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (235, 'Oona', 'Tamblingson', 'Jadranska ulica 5', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (236, 'Enoch', 'McOwen', 'Istarska ulica 3', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (237, 'Eleen', 'Sarchwell', 'Zadar', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (238, 'Steffen', 'Stannah', 'Zadar', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (239, 'Twyla', 'Francecione', 'Zagreb', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (240, 'Verile', 'Ditch', 'Split', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (241, 'Cherrita', 'Peggs', 'Slavonska ulica 10', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (242, 'Quinlan', 'Bodechon', 'Split', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (243, 'Elane', 'Murricanes', 'Slavonska ulica 10', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (244, 'Humbert', 'Clevely', 'Pula', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (245, 'Bentlee', 'Pietroni', 'Osijek', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (246, 'Corly', 'Ainscow', 'Split', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (247, 'Mireielle', 'Buckney', 'Dalmatinska ulica 7', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (248, 'Wenona', 'Pearsall', 'Zadar', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (249, 'Maxy', 'Clubley', 'Jadranska ulica 5', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (250, 'Bank', 'Alcorn', 'Slavonska ulica 10', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (251, 'Adiana', 'McIlmurray', 'Jadranska ulica 5', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (252, 'Kathleen', 'Clamo', 'Jadranska ulica 5', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (253, 'Noelani', 'Brymner', 'Zagreb', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (254, 'Eleni', 'Elcum', 'Osijek', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (255, 'Kaja', 'Georgeot', 'Slavonska ulica 10', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (256, 'Fee', 'Giorio', 'Istarska ulica 3', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (257, 'Finn', 'Causey', 'Istarska ulica 3', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (258, 'Simone', 'Malicki', 'Zadar', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (259, 'Claudius', 'McGeechan', 'Dalmatinska ulica 7', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (260, 'Daffy', 'Barnsdale', 'Osijek', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (261, 'Gretna', 'Clear', 'Split', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (262, 'Skipper', 'Chalcot', 'Zadar', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (263, 'Alameda', 'Worlidge', 'Pula', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (264, 'Gianni', 'Masson', 'Slavonska ulica 10', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (265, 'Rodina', 'Dowgill', 'Zadar', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (266, 'Alaric', 'Szantho', 'Istarska ulica 3', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (267, 'Sonya', 'Kensington', 'Slavonska ulica 10', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (268, 'Ruggiero', 'McGunley', 'Slavonska ulica 10', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (269, 'Lorrie', 'Petrie', 'Zagrebačka ulica 1', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (270, 'Alexander', 'Simper', 'Zagrebačka ulica 1', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (271, 'Juliana', 'Kefford', 'Zagrebačka ulica 1', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (272, 'Marshal', 'Austen', 'Zagrebačka ulica 1', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (273, 'Loy', 'Chiddy', 'Dalmatinska ulica 7', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (274, 'Nancey', 'Lynd', 'Jadranska ulica 5', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (275, 'Brad', 'Branscomb', 'Zagreb', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (276, 'Bellanca', 'Artus', 'Zagrebačka ulica 1', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (277, 'Meriel', 'Riply', 'Dalmatinska ulica 7', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (278, 'Lizette', 'Cornbill', 'Zadar', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (279, 'Aliza', 'Duplain', 'Zagreb', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (280, 'Minta', 'Olufsen', 'Istarska ulica 3', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (281, 'Giuditta', 'Blacker', 'Zagrebačka ulica 1', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (282, 'Prentiss', 'Perico', 'Pula', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (283, 'Guinevere', 'Waddingham', 'Split', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (284, 'Almeda', 'Shapira', 'Istarska ulica 3', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (285, 'Emerson', 'Janko', 'Zadar', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (286, 'Barrie', 'Benedit', 'Slavonska ulica 10', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (287, 'Arnaldo', 'Millhill', 'Jadranska ulica 5', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (288, 'Aylmer', 'Osgardby', 'Zagreb', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (289, 'Milt', 'Baldwin', 'Dalmatinska ulica 7', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (290, 'Melesa', 'Rothschild', 'Zagrebačka ulica 1', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (291, 'Adolpho', 'Kingsnorth', 'Istarska ulica 3', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (292, 'Massimiliano', 'Hanburry', 'Osijek', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (293, 'August', 'Keetley', 'Zagrebačka ulica 1', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (294, 'Ros', 'MacCosto', 'Dalmatinska ulica 7', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (295, 'Early', 'Deegin', 'Zadar', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (296, 'Noe', 'Colegrove', 'Slavonska ulica 10', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (297, 'Jemmie', 'Deehan', 'Zagreb', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (298, 'Inger', 'O''Gready', 'Zagrebačka ulica 1', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (299, 'Tadeo', 'Corzor', 'Dalmatinska ulica 7', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (300, 'Radcliffe', 'McGow', 'Osijek', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (301, 'Bartlet', 'Pering', 'Split', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (302, 'Dyanne', 'Gonzalez', 'Jadranska ulica 5', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (303, 'Gran', 'Dulake', 'Slavonska ulica 10', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (304, 'Sibylla', 'Taverner', 'Osijek', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (305, 'Morey', 'Menguy', 'Dalmatinska ulica 7', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (306, 'Vernen', 'Leupold', 'Slavonska ulica 10', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (307, 'Stacee', 'Do Rosario', 'Zadar', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (308, 'Justen', 'Thorrold', 'Slavonska ulica 10', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (309, 'Cleo', 'Dudney', 'Zagreb', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (310, 'Ilise', 'Neilan', 'Jadranska ulica 5', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (311, 'Artemis', 'Ziemsen', 'Slavonska ulica 10', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (312, 'Cordelia', 'Meeron', 'Dalmatinska ulica 7', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (313, 'Kayley', 'Scouller', 'Slavonska ulica 10', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (314, 'Ugo', 'Doherty', 'Zagrebačka ulica 1', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (315, 'Carlee', 'Digance', 'Zagreb', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (316, 'Florida', 'Davet', 'Zagreb', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (317, 'Charmian', 'Speares', 'Pula', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (318, 'Devy', 'Fenemore', 'Osijek', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (319, 'Valdemar', 'Cast', 'Istarska ulica 3', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (320, 'Bord', 'Power', 'Split', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (321, 'Reeba', 'Rippingale', 'Jadranska ulica 5', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (322, 'Selina', 'Kendred', 'Istarska ulica 3', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (323, 'Misty', 'Sayburn', 'Istarska ulica 3', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (324, 'Curt', 'Aitchinson', 'Slavonska ulica 10', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (325, 'Norman', 'Bockmann', 'Zagreb', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (326, 'Deidre', 'Sprowles', 'Dalmatinska ulica 7', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (327, 'Bronson', 'Sains', 'Zagreb', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (328, 'Dallas', 'Safont', 'Zagrebačka ulica 1', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (329, 'Tiebout', 'Romaine', 'Zagrebačka ulica 1', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (330, 'Barbara', 'Clerk', 'Slavonska ulica 10', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (331, 'Ambrose', 'Abramamovh', 'Slavonska ulica 10', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (332, 'Rozalie', 'Foxten', 'Pula', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (333, 'Adele', 'Kaszper', 'Zadar', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (334, 'Kary', 'Derwin', 'Pula', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (335, 'Pooh', 'Whaley', 'Pula', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (336, 'Anthony', 'Blasik', 'Split', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (337, 'Kally', 'Nornable', 'Split', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (338, 'Eddie', 'Osborne', 'Istarska ulica 3', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (339, 'Jaquelin', 'Wanless', 'Zagreb', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (340, 'Malva', 'Wherrit', 'Zagreb', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (341, 'Leena', 'Taylorson', 'Zagrebačka ulica 1', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (342, 'Wylma', 'Drover', 'Istarska ulica 3', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (343, 'Juliann', 'Mordy', 'Split', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (344, 'Jeramey', 'Benning', 'Slavonska ulica 10', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (345, 'Hildy', 'Delos', 'Istarska ulica 3', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (346, 'Tansy', 'Juorio', 'Osijek', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (347, 'Lishe', 'Dimblebee', 'Istarska ulica 3', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (348, 'Brendin', 'Gribble', 'Zagrebačka ulica 1', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (349, 'Cheri', 'Wither', 'Dalmatinska ulica 7', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (350, 'Jonie', 'Terlinden', 'Zadar', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (351, 'Darlleen', 'Bench', 'Zagrebačka ulica 1', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (352, 'Giustina', 'Jenk', 'Istarska ulica 3', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (353, 'Tatum', 'Antyshev', 'Istarska ulica 3', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (354, 'Roshelle', 'Honeywood', 'Slavonska ulica 10', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (355, 'Sibylle', 'Heineken', 'Slavonska ulica 10', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (356, 'Raphael', 'Dundendale', 'Jadranska ulica 5', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (357, 'Roddie', 'Loiterton', 'Zadar', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (358, 'Claudio', 'Browell', 'Zagreb', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (359, 'Halette', 'Newark', 'Osijek', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (360, 'Tiler', 'Hopkyns', 'Zadar', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (361, 'Idalina', 'Burgill', 'Dalmatinska ulica 7', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (362, 'Isidora', 'Meadus', 'Jadranska ulica 5', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (363, 'Nicolis', 'Iowarch', 'Split', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (364, 'Netti', 'Berthome', 'Zagrebačka ulica 1', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (365, 'Evelin', 'Simms', 'Zagrebačka ulica 1', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (366, 'Lindsay', 'Jenk', 'Split', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (367, 'Vito', 'Ing', 'Zagrebačka ulica 1', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (368, 'Merilyn', 'Biasotti', 'Osijek', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (369, 'Tiler', 'Thow', 'Pula', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (370, 'Lane', 'Blencoe', 'Pula', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (371, 'Israel', 'De Ortega', 'Jadranska ulica 5', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (372, 'Austin', 'Dripp', 'Dalmatinska ulica 7', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (373, 'Sib', 'Bellis', 'Zagrebačka ulica 1', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (374, 'Kippy', 'MacKimm', 'Split', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (375, 'Tucker', 'Jirus', 'Slavonska ulica 10', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (376, 'Anna-diane', 'Kippins', 'Istarska ulica 3', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (377, 'Alena', 'Rosander', 'Jadranska ulica 5', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (378, 'Breena', 'Maybey', 'Zagrebačka ulica 1', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (379, 'Shalne', 'Salmen', 'Pula', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (380, 'Napoleon', 'Boerderman', 'Pula', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (381, 'Addie', 'Goch', 'Slavonska ulica 10', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (382, 'Norah', 'Fairbourn', 'Zadar', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (383, 'Maye', 'Fosbraey', 'Osijek', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (384, 'Nettie', 'Botha', 'Slavonska ulica 10', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (385, 'Bat', 'Hounsom', 'Slavonska ulica 10', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (386, 'Auroora', 'Cockling', 'Istarska ulica 3', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (387, 'Golda', 'Springtorp', 'Jadranska ulica 5', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (388, 'Angelle', 'Pache', 'Dalmatinska ulica 7', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (389, 'Taddeusz', 'Bayldon', 'Zagrebačka ulica 1', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (390, 'Vanny', 'Mellsop', 'Zagrebačka ulica 1', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (391, 'Berna', 'Jedrzejewski', 'Osijek', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (392, 'Skyler', 'Rawling', 'Slavonska ulica 10', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (393, 'Phil', 'Joerning', 'Jadranska ulica 5', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (394, 'Arluene', 'Pollicote', 'Osijek', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (395, 'Grenville', 'Gascoyen', 'Osijek', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (396, 'Cicily', 'Tooke', 'Osijek', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (397, 'Allister', 'Mackie', 'Istarska ulica 3', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (398, 'Hilly', 'Bisp', 'Split', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (399, 'Corrina', 'Sandeland', 'Zadar', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (400, 'Aubrey', 'Mandrier', 'Istarska ulica 3', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (401, 'Niccolo', 'Wogan', 'Zadar', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (402, 'Kathe', 'Bertomier', 'Zagrebačka ulica 1', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (403, 'Arny', 'Forte', 'Zadar', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (404, 'Nani', 'Trusse', 'Slavonska ulica 10', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (405, 'Elliott', 'Varga', 'Osijek', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (406, 'Wini', 'Bailes', 'Istarska ulica 3', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (407, 'Tonya', 'Tirte', 'Zagreb', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (408, 'Reinhold', 'Brice', 'Split', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (409, 'Bel', 'Clutten', 'Osijek', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (410, 'Dulsea', 'Reeme', 'Zadar', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (411, 'Trish', 'Tortice', 'Zadar', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (412, 'Tally', 'Focke', 'Zagreb', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (413, 'Brendis', 'Tuting', 'Pula', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (414, 'Callida', 'Cotter', 'Pula', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (415, 'Witty', 'Yong', 'Slavonska ulica 10', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (416, 'Consuelo', 'Womack', 'Zagrebačka ulica 1', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (417, 'Kettie', 'Ridings', 'Zagrebačka ulica 1', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (418, 'Guinna', 'Belly', 'Pula', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (419, 'Wakefield', 'Perett', 'Zagreb', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (420, 'Tremaine', 'Sandry', 'Osijek', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (421, 'Carmel', 'Wivell', 'Jadranska ulica 5', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (422, 'Lucine', 'Deener', 'Split', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (423, 'Pinchas', 'Hanvey', 'Zagreb', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (424, 'Kristen', 'Collyer', 'Pula', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (425, 'Jessika', 'MacConneely', 'Zagreb', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (426, 'Augusto', 'Curryer', 'Zadar', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (427, 'Tanner', 'Scamwell', 'Jadranska ulica 5', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (428, 'Kiley', 'Blazewicz', 'Zadar', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (429, 'Nolan', 'Jendrassik', 'Zagrebačka ulica 1', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (430, 'Kelila', 'Bernth', 'Zagreb', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (431, 'Erskine', 'Arden', 'Split', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (432, 'Constantine', 'Trusse', 'Split', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (433, 'Ealasaid', 'Human', 'Istarska ulica 3', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (434, 'Arni', 'Fendlow', 'Zagreb', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (435, 'Siouxie', 'Linforth', 'Split', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (436, 'Durand', 'Satchel', 'Slavonska ulica 10', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (437, 'Rosamund', 'Suddards', 'Dalmatinska ulica 7', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (438, 'Sasha', 'Leates', 'Pula', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (439, 'Reggi', 'Stutard', 'Zagrebačka ulica 1', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (440, 'Honoria', 'Flacknell', 'Jadranska ulica 5', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (441, 'Emili', 'Bishop', 'Split', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (442, 'Urbanus', 'Aldhouse', 'Dalmatinska ulica 7', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (443, 'Frederico', 'Aylmore', 'Osijek', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (444, 'Adrianna', 'Ipgrave', 'Dalmatinska ulica 7', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (445, 'Vernor', 'Bordone', 'Pula', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (446, 'Joan', 'Hurll', 'Zadar', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (447, 'Gail', 'Klosterman', 'Split', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (448, 'Onfroi', 'Chaunce', 'Pula', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (449, 'Ward', 'Gracey', 'Split', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (450, 'Tatum', 'Paulton', 'Jadranska ulica 5', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (451, 'Lucias', 'Troutbeck', 'Split', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (452, 'Dorey', 'Orridge', 'Split', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (453, 'Shirlee', 'Dibben', 'Zagreb', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (454, 'Melonie', 'Lochran', 'Split', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (455, 'Grant', 'Dignon', 'Zagrebačka ulica 1', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (456, 'Chick', 'Kiellor', 'Dalmatinska ulica 7', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (457, 'Adrienne', 'Drews', 'Dalmatinska ulica 7', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (458, 'Judon', 'Halliday', 'Slavonska ulica 10', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (459, 'Leighton', 'Palfery', 'Dalmatinska ulica 7', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (460, 'Shaylynn', 'Turtle', 'Split', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (461, 'Tami', 'Desborough', 'Dalmatinska ulica 7', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (462, 'Waly', 'Kiwitz', 'Zagrebačka ulica 1', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (463, 'Shirlee', 'Gallelli', 'Zadar', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (464, 'Aurilia', 'Maudlin', 'Istarska ulica 3', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (465, 'Josy', 'Heatly', 'Dalmatinska ulica 7', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (466, 'Pat', 'Gregolin', 'Osijek', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (467, 'Quentin', 'Doerrling', 'Zagreb', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (468, 'Corly', 'Tippett', 'Split', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (469, 'Pippy', 'Torvey', 'Dalmatinska ulica 7', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (470, 'Jacqui', 'Carnock', 'Jadranska ulica 5', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (471, 'Simonne', 'Hagston', 'Jadranska ulica 5', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (472, 'Elene', 'Sherratt', 'Zagrebačka ulica 1', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (473, 'Sile', 'Siviour', 'Slavonska ulica 10', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (474, 'Deane', 'Provost', 'Zagrebačka ulica 1', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (475, 'Stacy', 'Deare', 'Slavonska ulica 10', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (476, 'Anton', 'Guilayn', 'Slavonska ulica 10', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (477, 'Wilek', 'Arnopp', 'Zagrebačka ulica 1', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (478, 'Cindee', 'Conklin', 'Dalmatinska ulica 7', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (479, 'Basile', 'Helliker', 'Split', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (480, 'Yorgo', 'Gradwell', 'Pula', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (481, 'Cleve', 'Darkott', 'Zagrebačka ulica 1', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (482, 'Orion', 'Bark', 'Jadranska ulica 5', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (483, 'Ginny', 'Housam', 'Osijek', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (484, 'Ethelred', 'Guite', 'Zagrebačka ulica 1', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (485, 'Leicester', 'Sprade', 'Zagreb', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (486, 'Dom', 'Irwin', 'Slavonska ulica 10', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (487, 'Kitti', 'Maleney', 'Split', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (488, 'Janot', 'Huburn', 'Dalmatinska ulica 7', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (489, 'Cristal', 'Kempson', 'Slavonska ulica 10', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (490, 'Jess', 'Singh', 'Jadranska ulica 5', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (491, 'Sim', 'Swayne', 'Split', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (492, 'Edmon', 'Palphramand', 'Dalmatinska ulica 7', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (493, 'Barret', 'Draye', 'Slavonska ulica 10', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (494, 'Murial', 'De Domenicis', 'Dalmatinska ulica 7', false);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (495, 'Dew', 'Geffinger', 'Zadar', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (496, 'Thayne', 'Nattriss', 'Istarska ulica 3', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (497, 'Emmeline', 'Zammett', 'Zagrebačka ulica 1', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (498, 'Magdalene', 'Garwell', 'Osijek', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (499, 'Ephraim', 'McCarry', 'Zagrebačka ulica 1', true);
insert into UserInfo (UserId, UserName, UserSurname, UserAdress, LoyaltyCard) values (500, 'Natka', 'Townsley', 'Osijek', true);
